events {}

http {
    resolver 127.0.0.11 valid=10s;

    server {
        listen 80;

        location /api/auth/ {
            set $auth auth_backend;
            proxy_pass http://$auth:9999;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;


            proxy_set_header Cookie $http_cookie;

            proxy_connect_timeout 2s;
            proxy_read_timeout 10s;
            proxy_next_upstream error timeout http_502 http_503 http_504;
        }

        location /api/img/ {
            set $img img_backend;
            proxy_pass http://$img:9998;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;


            proxy_set_header Cookie $http_cookie;

            proxy_connect_timeout 2s;
            proxy_read_timeout 10s;
            proxy_next_upstream error timeout http_502 http_503 http_504;
        }
    }
}